FROM node:20-alpine

WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias normales y ts-node-dev globalmente
RUN npm install
RUN npm install -g ts-node-dev

# Copiar el resto del código
COPY . .

# Exponer el puerto de la app
EXPOSE 4000

# Comando para desarrollo
CMD ["ts-node-dev", "--respawn", "--transpile-only", "src/index.ts"]
